// ============================================================
// Terms of Service — YupSoul Content Manager
// URL: /terms
// ============================================================

export const metadata = {
  title: 'Terms of Service — YupSoul Content Manager',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen p-6 md:p-12">
      <article className="max-w-3xl mx-auto text-[var(--nebula-gray)] leading-relaxed">
        <h1 className="text-3xl font-bold gold-accent mb-2">Terms of Service</h1>
        <p className="text-sm text-[var(--nebula-gray)] mb-8">Last updated: April 13, 2026</p>

        <section className="space-y-6">
          <div>
            <h2 className="text-xl font-semibold text-[var(--star-white)] mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing and using YupSoul Content Manager (&quot;the App&quot;), you agree
              to be bound by these Terms of Service. If you do not agree, please do not use the App.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-[var(--star-white)] mb-2">2. Description of Service</h2>
            <p>
              YupSoul Content Manager is a content management tool that generates and publishes
              astrology and AI-music related content to social media platforms on behalf of
              authorized users. The App is part of the YupSoul ecosystem — a Telegram Mini App
              that creates personalized AI-music compositions based on astrological profiles.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-[var(--star-white)] mb-2">3. User Responsibilities</h2>
            <p>By using the App, you agree to:</p>
            <ul className="list-disc ml-6 mt-2 space-y-1">
              <li>Provide accurate account information</li>
              <li>Only connect accounts you own or have authorization to manage</li>
              <li>Comply with TikTok&apos;s Community Guidelines and Terms of Service</li>
              <li>Not use the App to publish prohibited, harmful, or illegal content</li>
              <li>Not attempt to reverse-engineer or exploit the App</li>
            </ul>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-[var(--star-white)] mb-2">4. Content Ownership</h2>
            <p>
              Content generated by the App using AI is created for your use. You retain
              the right to publish, modify, or remove generated content. The App does not
              claim ownership of content published to your social media accounts.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-[var(--star-white)] mb-2">5. AI-Generated Content</h2>
            <p>
              The App uses artificial intelligence to generate text and images.
              While we strive for quality and accuracy, AI-generated content may
              occasionally be inaccurate, inappropriate, or require human review.
              You are responsible for reviewing content before or after publication.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-[var(--star-white)] mb-2">6. Third-Party Services</h2>
            <p>
              The App integrates with third-party platforms (TikTok, etc.).
              Your use of these platforms is subject to their own terms of service.
              We are not responsible for changes to third-party APIs or policies.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-[var(--star-white)] mb-2">7. Limitation of Liability</h2>
            <p>
              The App is provided &quot;as is&quot; without warranties of any kind. We are not
              liable for any damages resulting from the use or inability to use the App,
              including but not limited to: account suspension by third-party platforms,
              content removal, or loss of data.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-[var(--star-white)] mb-2">8. Termination</h2>
            <p>
              You may stop using the App at any time by disconnecting your accounts.
              We reserve the right to suspend or terminate access to the App for
              violation of these terms.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-[var(--star-white)] mb-2">9. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Changes will be posted
              on this page. Continued use of the App after changes constitutes
              acceptance of the updated terms.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold text-[var(--star-white)] mb-2">10. Contact</h2>
            <p>
              For questions about these Terms, contact us via:{' '}
              <a href="https://t.me/Yup_Soul_bot?start=ref_miplix" className="lavender-accent hover:underline">
                @Yup_Soul_bot
              </a>
            </p>
            <p className="mt-2">
              Website:{' '}
              <a href="https://www.yupsoul.online/" className="lavender-accent hover:underline">
                yupsoul.online
              </a>
            </p>
          </div>
        </section>
      </article>
    </div>
  );
}
